#!/usr/bin/perl

$cache = $ARGV[0];
$update_file = $ARGV[1];

use XML::LibXML;
use Digest::SHA1;
use URI::Escape;

sub video_duration {
    my $entry = shift;
    return ($entry->getElementsByTagName('yt:duration'))[0]->getAttribute("seconds");
}

# Given a search term, return the URL.
sub get_video_id {
    my $search = shift;
    my $length = shift;
    print "Searching for $search ($length)\n";
    system("curl",
	   "-s",
	   "-o", "/tmp/flutter.url",
	   "https://gdata.youtube.com/feeds/api/videos?q=$search&max-results=2&v=2");
    
    my $parser = XML::LibXML->new();
    my $xmldoc = $parser->parse_file("/tmp/flutter.url");

    my @entries = $xmldoc->getElementsByTagName('entry');

    if ($#entries < 1) {
	print "Can't find URL\n";
	return;
    }

    # Sort the results so that we choose the video that has the length
    # that's closest to our target song.
    @entries = sort { abs($length - video_duration($a)) <=>
			  abs($length - video_duration($b)) } @entries;

    my $best_entry = $entries[0];
    print "Best length is " . video_duration($best_entry) . "\n";
    my $url = ($best_entry->getElementsByTagName('content'))[0]->getAttribute("src");
    print "$url\n";
    if ($url =~ /com\/v\/([-a-zA-Z0-9]+)\?/) {
	return $1;
    } else {
	return;
    }
}

sub kill_mplayer {
    my $pid = shift;
    if ($pid) {
	print "Killing player $pid\n";
	kill 9, $pid;
	system("kill", "-9", "$pid");
    }
    system("pkill mplayer");
}

sub duration {
    my $file = shift;
    open(my $fd, "-|", "mp3info", "-x", "-F", "-r", "a", $file);
    my $length;
    while (<$fd>) {
	if (/^Length: +([0-9]+):([0-9]+)/) {
	    $length = $1*60 + $2;
	}
    }
    close $fd;
    return $length;
}

sub play_url {
    my $url = shift;
    while (true) {
	system("mplayer",
	       "-volume", "0",
	       "-softvol",
	       "-msglevel", "all=-1",
	       "-zoom", "-fs",
	       "-display", ":1",
	       $url);
    }
    exit(0);
}

sub refresh {
    open(UF, $update_file);
    my $current = <UF>;
    close UF;

    chop($current);
    my @current = split("/", $current);

    my $track = $current[$#current];
    $track =~ s/^[0-9][0-9]-|.mp3$//g;

    my $artist = uri_escape($current[$#current - 2]);
    my $album = uri_escape($current[$#current - 1]);
    $track = uri_escape($track);

    my $length = duration($current);
    my $video_id = get_video_id("$artist+$album+$track", $length);
    
    if (! $video_id) {
	$video_id = get_video_id("$artist+$track", $length);
    }
    
    if ($video_id) {
	my $url = `youtube-dl -g 'http://www.youtube.com/watch?v=$video_id&feature=related'`;
	print "url $url\n";
	if ($url) {
	    chop($url);
	    my $old_pid = $mplayer_pid;
	    $mplayer_pid = fork();
	    if ($mplayer_pid) {
		return;
	    } else {
		kill_mplayer($old_pid);
		play_url($url);
	    }
	}
    }
}

while (true) {
    $timestamp = (stat($update_file))[9];
    if ($timestamp > $last_timestamp) {
	refresh();
    }
    $last_timestamp = $timestamp;
    sleep(1);
}
