#!/usr/bin/perl

$cache = $ARGV[0];
$update_file = $ARGV[1];

use XML::LibXML;
use Digest::SHA1;
use URI::Escape;

sub get_url {
    my $search = shift;
    print "Searching for $search\n";
    system("curl",
	   "-s",
	   "-o", "/tmp/flutter.url",
	   "https://gdata.youtube.com/feeds/api/videos?q=$search&max-results=1&v=2");
    
    $parser = XML::LibXML->new();
    $xmldoc = $parser->parse_file("/tmp/flutter.url");
    
    for $content ($xmldoc->getElementsByTagName('content')) {
	$url = $content->getAttribute("src");
    }
    
    if (! $url) {
	print "Can't find URL\n";
    }
    return $url;
}

sub play_file {
    my $file = shift;
    system("pkill mplayer");
    exec("mplayer",
	 "-volume", "0",
	 "-softvol",
	 "-zoom", "-fs",
	 "-display", ":1",
	 "-loop", "0",
	 $file);
}

sub refresh {
    open(UF, $update_file);
    $current = <UF>;
    close UF;

    chop($current);
    my @current = split("/", $current);

    my $track = $current[$#current];
    $track =~ s/^[0-9][0-9]-|.mp3$//g;

    my $artist = uri_escape($current[$#current - 2]);
    my $album = uri_escape($current[$#current - 1]);
    $track = uri_escape($track);

    my $url = get_url("$artist+$album+$track");
    
    if (! $url) {
	$url = get_url("$artist+$track");
    }
    
    if ($url) {
	#$hash = Digest::SHA1::sha1_base64($url);
	my $hash = $current[$#current - 2] . "_" .
	    $current[$#current - 1] . "_" .
	    $current[$#current] . ".flv";
	
	if (! -f "$cache/$hash") {
	    if (fork()) {
		return;
	    } else {
		print "Downloading $url $hash\n";
		if (! fork()) {
		    system("youtube-dl",
			   "-o", "$cache/$hash",
			   $url);
		    exit(0);
		}
		sleep(5);
		$mplayer_pid = $$;
		if (-f "$cache/$hash") {
		    play_file("$cache/$hash");
		} elsif (-f "$cache/$hash.part") {
		    play_file("$cache/$hash.part");
		}
		exit(0);
	    }
	}
	
	if (-f "$cache/$hash") {
	    if ($mplayer_pid) {
		kill 9, $mplayer_pid;
	    }
	    $mplayer_pid = fork();
	    if (! $mplayer_pid) {
		play_file("$cache/$hash");
		exit(0);
	    }
	}
    }
}

while (true) {
    $timestamp = (stat($update_file))[9];
    if ($timestamp > $last_timestamp) {
	refresh();
    }
    $last_timestamp = $timestamp;
    print "Sleeping...\n";
    sleep(1);
}

