#!/bin/bash

# This is just a wrapper around mpv that outputs the total mean
# bitrate at the end (and that exits if the bitrate is below the
# optional cutoff.
#
# It requires socat (to talk to a socket) and jq (to parse JSON).  And
# mpv, to play a video.

url="$1"
type="$2"
cutoff="$3"

if [ "$url" = "" ]; then
    echo "Usage: $0 <url> [type cutoff]"
    exit
fi

tmp="/tmp/flutter"

if [ ! -d "$tmp" ]; then
   mkdir "$tmp"
fi

socket="$tmp/mpv-$$"

function clean {
    if [ -e "$socket" ]; then
	rm "$socket"
    fi

    if [ -e "$tmp/flutter1.jpg" ]; then
	rm "$tmp/flutter1.jpg"
    fi
    
    if [ -e "$tmp/flutter2.jpg" ]; then
	rm "$tmp/flutter2.jpg"
    fi
}

function cleankill {
    kill $mpv
    clean
    results
    exit
}

trap clean EXIT
trap cleankill SIGINT SIGTERM

function results {
    if [ $times -gt 0 ]; then
	echo -n $(($total / $times))
    else
	echo -n 0
    fi

    echo -n " "

    if [ $difftimes -gt 0 ]; then
	echo 4 k $totaldiff $difftimes / p | dc
    else
	echo 1
    fi
}

clean

#PATH=$PATH:/home/larsi/.local/bin /usr/src/mpv/build/mpv --no-stop-screensaver -vo=x11 --no-audio --quiet --input-ipc-server="$socket" "$url" 2>/dev/null >/dev/null &

#  

~/src/mpv/build/mpv --msg-level=all=info --hwdec=no --vd=lavc:libaom-av1 --panscan=1.0 --no-stop-screensaver --no-audio --fs --no-osc --input-ipc-server="$socket" "$url" 2>>/tmp/mpv.log >>/tmp/mpv.log &

mpv="$!"

times=0
difftimes=0
totaldiff=0
while ps -p $mpv >/dev/null; do
    data=$(echo '{ "command": ["get_property", "video-bitrate"] }' | socat - "$socket")
    echo "Data $data\n" >> /tmp/data
    state=$(jq -r .error <<< "$data")
    if [ "$state" = "success" ]; then
	rate=$(jq -r .data <<< "$data")
	total=$(($total + $rate))
	times=$(($times + 1))

	if [ $times -lt 20 ]; then
	    if [ -e "$tmp/flutter1.jpg" -a -e "$tmp/flutter2.jpg" ]; then
		diff=$(compare -metric NCC "$tmp/flutter1.jpg" "$tmp/flutter2.jpg" null: 2>&1)
		if ! echo "$diff" | grep compare >/dev/null; then
		    difftimes=$(($difftimes + 1))
		    echo "Diff '$diff'" >> $tmp/diffs
		    totaldiff=$(echo $totaldiff $diff + p | dc)
		fi
	    fi

	    if [ $(($times % 2)) -eq 0 ]; then
		rm -f $tmp/flutter1.jpg
		socat - "$socket" >/dev/null <<< "{ \"command\": [\"screenshot-to-file\", \"$tmp/flutter1.jpg\"] }"
	    else
		rm -f $tmp/flutter2.jpg
		socat - "$socket" >/dev/null <<< "{ \"command\": [\"screenshot-to-file\", \"$tmp/flutter2.jpg\"] }"
	    fi
	fi

	if [ "$cutoff" != "" ]; then
	    if [ "$type" = "rate" ]; then
		if [ $(($total / $times)) -lt "$cutoff" ]; then
		    clean
		    results
		    exit
		fi
	    else
		if [ $difftimes -gt 4 ]; then
		    diff=$(echo 4 k $totaldiff $difftimes / 10000 \* p | dc | sed 's/[.].*//')
		    cut=$(echo 4 k $cutoff 1 / 10000 \* p | dc | sed 's/[.].*//')
		    if [ $diff -gt $cut ]; then
			clean
			results
			# We have a too silent video, so kill it.
			kill -9 $mpv
			exit
		    else
			# We have a successful video, so kill all
			# other mpvs that may be running in the
			# background.
			for opid in `pgrep -f build/mpv`; do
			    if [ "$opid" -ne "$mpv" ]; then
				echo "Killing $opid and its parents because it's not $mpv" >> /tmp/kill.log
				parent=`ps -o ppid= $opid`
				pparent=`ps -o ppid= $parent`
				echo "Killing $pparent $parent $opid" >> /tmp/kill.log
				kill $pparent $parent $opid
			    fi
			done
			# Don't kill any new videos, though.
			cutoff=""
		    fi
		fi
	    fi
	    
	fi
    fi
    sleep 1
done

clean
results
