#!/usr/bin/perl

# I'm unsure where this program came from.  I doubt that I've written
# it myself (due to the coding style), so I must have found it
# somewhere.

use X11::Protocol;
use Tk;

$x = X11::Protocol->new();

sub get_window_by_name {
    _get_window_by_name($x->{'root'}, $_[0]);
}

@windows = ();

sub _get_window_by_name {
    my($root, $searchname) = @_;
    my($dummy, $dummy2, @new_kids) = $x->QueryTree($root);
    foreach my $k (@new_kids) {
	my $atomnr;
	#warn sprintf("%x\n", $k);
	foreach my $atom ($x->ListProperties($k)) {
	    if ($x->GetAtomName($atom) eq "WM_CLASS") {
		$atomnr = $atom;
		last;
	    }
	}
	if (defined $atomnr) {
	    my($classprop) = $x->GetProperty($k, $atomnr, "AnyPropertyType",
					     0, 256, 0);
	    my($class, $name) = split(/\0/, $classprop);
	    if ($class =~ /$searchname/) {
		push @windows, $k;
	    }
	}
	my $ret = _get_window_by_name($k, $searchname);
	if (defined $ret) {
	    push @windows, $ret;
	}
    } undef;
}


$name = $ARGV[0];

get_window_by_name($name);
foreach (@windows) {
    $x->ConfigureWindow($_, 'stack_mode' => Above);
}
